use_frameworks!

target 'LGInternationalization_Example' do
  pod 'LGInternationalization', :path => '../'

  target 'LGInternationalization_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
