source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/applekwork/LGInternationalization.git'

target 'LGInternationalization_Example' do
  pod 'LGInternationalization', :path => '../'
  pod 'MBProgressHUD', '0.9.2'
  target 'LGInternationalization_Tests' do
    inherit! :search_paths
  end
end
